# 前端 Dockerfile
FROM mirror.gcr.io/library/nginx:alpine

# 删除默认配置
RUN rm /etc/nginx/conf.d/default.conf

# 复制构建产物
COPY devtools-hub/dist /usr/share/nginx/html

# 复制 Nginx 配置
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
